export const colorPrimary = '#1652dd';
export const colorSuccess = '#039c28';
export const colorWarning = '#dc6d04';
export const colorError = '#d3393a';
export const colorInfo = '#1652dd';
export const colorTextBase = '#ffffff'; // 基础文本色
export const colorBgBase = '#000000'; // 基础背景色
export const colorText = '#ebeced'; // 一级文本色
export const colorTextSecondary = '#babdc2'; // 二级文本色
export const colorTextTertiary = '#6f747e'; // 三级文本色
export const colorTextQuaternary = '#4a4f5a'; // 四级文本色
export const colorBorder = '#313540'; // 一级边框
export const colorBorderSecondary = '#1e212a'; // 二级边框色
export const colorFill = '#313540'; // 一级填充色
export const colorFillSecondary = '#1e212a'; // 二级填充色
export const colorFillTertiary = '#13151c'; // 三级填充色
export const colorFillQuaternary = '#090a0f'; // 四级填充色
export const colorFillFifth = '#2e3140'; // 五级填充色
export const colorBgContainer = '#13151c';
export const colorBgElevated = '#1e212a';
export const colorBgLayout = '#090a0f';
export const colorBgSpotlight = '#000000d9';
export const colorBgMask = '#00000073';
